### PR TITLE
Next v3

### PR DESCRIPTION
**Pull request by jxnblk**
Rebass v3 is a complete rewrite with the intent of making this UI component library useful to an even wider audience. Instead of trying to provide an off-the-shelf solution to styling UI (there are several other libraries out there for that), it tries to provide a solid base for extending these components into a highly customized UI component library. Rebass is intended to be useful in *any* React application and is so small it shouldn't make a huge impact on your overall bundle size.

- Much smaller (~1KB)
- 8 components: Box, Flex, Text, Heading, Button, Link, Image, and Card
- Built with styled-components v4
- Intended to be extended
- Only one dependency: styled-system
- No default theme or colors
- No Provider component required
- Variant theme support for Button and Card
- Demo: https://rebass.now.sh

```sh
npm i rebass@next
```

## Changes

- Removes 61 components
- Removes `system-components` (`@rebass/components`), `grid-styled` (`@rebass/grid`), and `polished` dependencies
- Removes the `is` prop in favor of styled-components' `as` prop
- All components extend the base `Box` component
- v3 should still be compatible with previous versions of styled-components and emotion

###  Where'd all the components go?

They're still here in spirit :ghost: They might come back to haunt you in separate, more modular packages.

The overall reduction in size of this codebase and splitting Rebass up into more modular packages will give users much more control over the size of their application bundles and allow a lot more flexibility in terms of building out custom libraries.

### Why has system-components (`@rebass/components`) been removed?

It adds a lot of overhead and complexity to the codebase, and most end-users don't benefit from it being used in Rebass.

### Why are style props showing in the HTML

This is a [long standing issue with styled-components][sc-issue] and is due to the way the `styled` higher-order component is implemented. I was hopeful that styled-components v4 would have addressed this issue to avoid some of the less-than-ideal solutions used in the previous version of Rebass, but that will have to wait. And, due to the introduction of the `as` prop in styled-components, attempting to work around this issue while keeping up with the changing landscape of CSS-in-JS libraries doesn't seem worth it for a simple library like Rebass. That said, there *might* be a Babel plugin introduced in the future to help with this issue.

Related:

- https://github.com/styled-components/styled-components/issues/1981#issuecomment-419287003

### What's happening with @rebass/grid (formerly grid-styled)?

The `@rebass/grid` package will be updated to match the APIs of the Box and Flex component here (which is virtually the same) and will be available as an even smaller alternative to this library.

### Why has the Provider and theme been removed?

In order to remain as unopinionated as possible, themes are now optional, giving you complete control over what your application looks like. Separate theme packages might be introduced to provide some smart defaults.

### Version 2

v2 will still be available in a branch to continue development while v3 is in beta. Any pull requests for v2 should point to that branch.

[sc-issue]: https://github.com/styled-components/styled-components/issues/439

### CODE REVIEW

**Comment by jxnblk** [comment]
I'm planning on merging this into master to continue development on v3. The package will be tagged `next` and the `latest` version will still point to v2 until 3 is out of beta. For any continued work on v2, please point PRs to the v2 branch.

**Comment by gi-alec** [comment]
Does v3 no longer support extending components with conventional styled-components template literals?

**Comment by jxnblk** [comment]
You can use whatever syntax you want to extend the components. In styled-components v4, the `.extend` method is deprecated though fwiw

**Comment by TrySound** [comment]
@jxnblk `as` doesn't work in emotion yet. Can we polyfill it by using rename-import babel plugin?

**Comment by gi-alec** [comment]
@jxnblk Ah lovely. I misinterpreted the documentation

> There are two **primary** ways to extend Rebass components

as

> There are two ways to extend Rebass components

**Comment by jxnblk** [comment]
@TrySound how would you imagine polyfilling that prop? I can add a note to the docs, but I'd assume that emotion users should be familiar with the `.withComponent` API...

**Comment by TrySound** [comment]
@jxnblk Heh, I should've be familiar with this api. Thanks for the lesson :)

**Comment by jxnblk** [comment]
@TrySound no worries. v2 of Rebass tried to "polyfill" this behavior with the clean-tag and system-components modules, which ended up being less-than-ideal. Hopefully the `as` prop lands in emotion, since it's a more flexible/more react-like API than the method chaining stuff

**Comment by TrySound** [comment]
@jxnblk Maybe it's better to use more universal `withComponent` api instead of `as` prop in `defaultProps`?

**Comment by jxnblk** [comment]
Part of the thinking behind the major v3 bump was to rely on the `as` prop, and I've run into issues with the `withComponent` API in the past that I'd want to avoid in this library.

**Comment by TrySound** [comment]
Well, then emotion version won't be correct until they land `as` prop.

**Comment by bessey** [comment]
This comment is very late to the party, but here goes... I like the direction you're going with v3 conceptually @jxnblk. I love Rebass 2, use it extensively at my work, and agree that it makes sense to have a version of Rebass with a narrower API.

...But (sorry 😅), "Removes 61 components" is not just a major version bump. As it stands, v3 is not the same library anymore. The upgrade path from v2 to v3 is currently **re-implement 2/3rds of the library in your app, because we removed most of the public API**. It reminds me of when React Router completely changed its API, angering a bunch of people, and to my knowledge is unheard of outside the JS community.

I could understand if, as you suggest, the removed components are extracted to a separate library, but that hasn't happened yet. Which would also be fine, after all this is a pre-release, but right now the official site points to the v3 pre release with a tiny link to the v2 docs at the bottom. Functionally, the docs imply this is the version to use. I'm trying to onboard other engineers to Rebass v2 based apps and I'm having to tell them "You have to ignore these docs because they're for a pre-release 'version' that removes the majority of the API we're using", which is deeply confusing. If someone reads docs for the wrong version of Next or Rails or whatever, they might think they have access to some features that they don't, but this is a whole different library.

Perhaps the confusion could be reduced by doing at least _some_ of the following:
- Point rebassjs.org at the current release version, not a pre-release
- Or make the fact its a pre-release with colossal amounts of breaking changes, and a link to v2, more prominent
- Release the removed components as a package that can be re-imported by v2 users
- Document the migration path from v2 to v3
- If there is no intended migration path, i.e. no other source to get the many removed components from... Don't call v3 `rebass`

_Please know that I love your library_.

**Comment by pauldariye** [comment]
Thanks clearly articulating this @bessey. I just ran into this issue. I had used rebass a while back when it still had the components in v2. I assumed v3 was moving in the direction, only to find out it is entirely different.

@jxnblk, I <3 rebass and would love to get involved in migrating all the components of v2 to a new library and maybe have it be backward compatible. Happy to send an email to you. I've been getting into style systems and this looks like a well-scoped project to take on.

**Comment by jxnblk** [comment]
@bessey Thanks for the feedback, and I think I understand where you're coming from, but my priorities for this project are to make sure it reflects the latest thinking into how I'd recommend building out UI component libraries. While some people do use many of the components available in v2, there are other libraries out there that provide similar number of components that could be used instead of Rebass.

**If you are really invested in the v2 API, this project is open source, and I'd highly recommend forking it.**

Alternatively, you can keep some of those components in your own application's source code, which would give you full control over the implementation. This is similar to how I sense that most people are using styled-system, and I think it's a fine approach. 

I do not have the time to maintain the previous version of Rebass. If anyone would like to help port some of the old components over to separate packages that reflect the current implementation, I'd consider linking to them. Additionally, for where I'd like the library to go in the future, I don't think the previous v2 API makes sense to keep around or promote as a way of building out component libraries.

That said, I do plan to add a migration doc to clearly state the changes and provide options for how to migrate to v3

**Pull request merged**
