### PR TITLE
Build packages

### PR DESCRIPTION
**Pull request by TrySound**
In this diff I provided a build script for each package in this monorepo.
The structure looks like this one

```
packages/
  module
    emotion/package.json
    dist/package.json
    dist/index.cjs.js
    dist/index.esm.js
    dist/emotion.cjs.js
    dist/emotion.esm.js
```

Pkg specifies `main` and `module` fields for styled components and for
emotion.

### CODE REVIEW

**Comment by TrySound** [comment]
I'm not sure how to fix deploy error. Travis works fine.
/cc @jxnblk

**Comment by jxnblk** [comment]
I'd rather hold off on all these build changes until after v3 is released

**Comment by TrySound** [comment]
They may be breaking. It should be landed in v3. What's the problem?

**Comment by jxnblk** [comment]
Why would the build process be breaking changes?

**Comment by TrySound** [comment]
Because the result of build process is different.

Everything should be landed and tested before major release or users will get shit in minor and patches.

**Comment by TrySound** [comment]
This is the point of prereleases.

**Comment by TrySound** [comment]
Fuck. Will build my own framework. Contribution to your projects makes me tired.

**Pull request closed without merging**
